=== CWill22/K-FinalProject/src/store/products_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <!-- Definition of the Product element -->
  <xs:element name="Product">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Name" type="xs:string"/>
        <xs:element name="Type" type="xs:string"/>
        <xs:element name="Brand" type="xs:string"/>
        <xs:element name="Color" type="xs:string"/>
        <xs:element name="Size" type="xs:string"/>
        <xs:element name="Material" type="xs:string"/>
        <xs:element name="Gender" type="xs:string"/>
        <xs:element name="Price" type="xs:decimal"/>
        <xs:element name="QuantityInStock" type="xs:integer"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Definition of the root element that contains multiple Product elements -->
  <xs:element name="Project">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Product" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== CWill22/K-FinalProject/src/store/clothingInventory.xml
<?xml version="1.0" encoding="UTF-8"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="products_schema.xsd">
   <Product>
    
    
    <Name>Mizzou Short</Name>
    
    
    <Type>Short</Type>
    
    
    <Brand>NEW_ERA</Brand>
    
    
    <Color>WHITE</Color>
    
    
    <Size>XL</Size>
    
    
    <Material>POLYESTER</Material>
    
    
    <Gender>UNISEX</Gender>
    
    
    <Price>36</Price>
    
  
    <QuantityInStock>13</QuantityInStock>
  </Product>
  
  
  <Product>
    
    
    <Name>Mizzou TShirt</Name>
    
    
    <Type>TShirt</Type>
    
    
    <Brand>NIKE</Brand>
    
    
    <Color>GOLD</Color>
    
    
    <Size>S</Size>
    
    
    <Material>COTTON</Material>
    
    
    <Gender>WOMEN</Gender>
    
    
    <Price>54</Price>
    
  
    <QuantityInStock>97</QuantityInStock>
  </Product>
  
  
  <Product>
    
    
    <Name>Mizzou Sweatpant</Name>
    
    
    <Type>Sweatpant</Type>
    
    
    <Brand>UNDER_ARMOUR</Brand>
    
    
    <Color>WHITE</Color>
    
    
    <Size>XS</Size>
    
    
    <Material>POLYESTER</Material>
    
    
    <Gender>MEN</Gender>
    
    
    <Price>51</Price>
    
  
    <QuantityInStock>20</QuantityInStock>
  </Product>
  
  
  <Product>
    
    
    <Name>Mizzou Sweatshirt</Name>
    
    
    <Type>Sweatshirt</Type>
    
    
    <Brand>NIKE</Brand>
    
    
    <Color>BLACK</Color>
    
    
    <Size>S</Size>
    
    
    <Material>COTTON</Material>
    
    
    <Gender>UNISEX</Gender>
    
    
    <Price>35</Price>
    
  
    <QuantityInStock>93</QuantityInStock>
  </Product>
  
  
  <Product>
    
    
    <Name>Mizzou TShirt</Name>
    
    
    <Type>TShirt</Type>
    
    
    <Brand>NIKE</Brand>
    
    
    <Color>WHITE</Color>
    
    
    <Size>L</Size>
    
    
    <Material>COTTON</Material>
    
    
    <Gender>WOMEN</Gender>
    
    
    <Price>22</Price>
    
  
    <QuantityInStock>20</QuantityInStock>
  </Product>
  
  
  <Product>
    
    
    <Name>Mizzou Sock</Name>
    
    
    <Type>Sock</Type>
    
    
    <Brand>NEW_ERA</Brand>
    
    
    <Color>WHITE</Color>
    
    
    <Size>XS</Size>
    
    
    <Material>POLYESTER</Material>
    
    
    <Gender>MEN</Gender>
    
    
    <Price>17</Price>
    
  
    <QuantityInStock>22</QuantityInStock>
  </Product>
  
  
  <Product>
    
    
    <Name>Mizzou Crewneck</Name>
    
    
    <Type>Crewneck</Type>
    
    
    <Brand>ADIDAS</Brand>
    
    
    <Color>BLACK</Color>
    
    
    <Size>XXL</Size>
    
    
    <Material>COTTON</Material>
    
    
    <Gender>WOMEN</Gender>
    
    
    <Price>16</Price>
    
  
    <QuantityInStock>18</QuantityInStock>
  </Product>
  
  <Product>
    
    
    <Name>Mizzou Sock</Name>
    
    
    <Type>Sock</Type>
    
    
    <Brand>NIKE</Brand>
    
    
    <Color>BLACK_AND_GOLD</Color>
    
    
    <Size>ONE_SIZE</Size>
    
    
    <Material>WOOL</Material>
    
    
    <Gender>UNISEX</Gender>
    
    
    <Price>17</Price>
    
  
    <QuantityInStock>15</QuantityInStock>
  </Product>

</Project>
